### ISSUE TITLE
New release 2.2.0 error

### ISSUE THREAD

**Issue by jcastro** [home-assistant/homebridge-homeassistant#188]
Hello!
Just updated to the new plugin but I'm getting this error
```
[7/19/2017, 2:49:58 PM] Loaded plugin: homebridge-cmdswitch2
[7/19/2017, 2:49:58 PM] Registering platform 'homebridge-cmdswitch2.cmdSwitch2'
[7/19/2017, 2:49:58 PM] ---
[7/19/2017, 2:49:58 PM] Loaded plugin: homebridge-homeassistant
[7/19/2017, 2:49:58 PM] Registering platform 'homebridge-homeassistant.HomeAssistant'
[7/19/2017, 2:49:58 PM] ---
[7/19/2017, 2:49:58 PM] Loaded config.json with 0 accessories and 2 platforms.
[7/19/2017, 2:49:58 PM] ---
[7/19/2017, 2:49:58 PM] Loading 2 platforms...
[7/19/2017, 2:49:58 PM] [HomeAssistant] Initializing HomeAssistant platform...
[7/19/2017, 2:49:58 PM] [HomeAssistant] Fetching HomeAssistant devices.
[7/19/2017, 2:49:58 PM] [ CMD switch] Initializing cmdSwitch2 platform...
[7/19/2017, 2:49:58 PM] [ CMD switch] Initializing platform accessory 'jonatan isHome'...
[7/19/2017, 2:49:58 PM] [HomeAssistant] Received event: ping
/usr/lib/node_modules/homebridge-homeassistant/accessories/sensor.js:107
} else if (data.attributes.unit_of_measurement.toLowerCase() === 'lux' || data.attributes.homebridge_sensor_type === 'light') {
^

TypeError: Cannot read property 'toLowerCase' of undefined
at HomeAssistantSensorFactory (/usr/lib/node_modules/homebridge-homeassistant/accessories/sensor.js:107:49)
at request (/usr/lib/node_modules/homebridge-homeassistant/index.js:179:23)
at Request.request [as _callback] (/usr/lib/node_modules/homebridge-homeassistant/index.js:96:7)
at Request.self.callback (/usr/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:188:22)
at emitTwo (events.js:106:13)
at Request.emit (events.js:191:7)
at Request.<anonymous> (/usr/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:1171:10)
at emitOne (events.js:96:13)
at Request.emit (events.js:188:7)
at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:1091:12)
```
I'm running Homebridge inside a docker on top of unRaid

**Comment by Bjsulla** [comment]
Getting the same error when not running in docker.

**Comment by jcastro** [comment]
Looking at my config I've a few devices configured like this:
```
### Oficina ###
# Luces
  switch.wall_switch_right_158d00014a9626:
    icon: mdi:toggle-switch
    friendly_name: Luz
    homebridge_switch_type: light
```
So these are some Zigbee Wall switches that were showing up in HomeKit as switches so I set them to lights in HomeKit

**Comment by jcastro** [comment]
Tried commenting the 'homebridge_switch_type: light' line but no luck

**Comment by Bjsulla** [comment]
Downgraded to version 2.1.0 and it then runs successfully.
`npm install -g homebridge-homeassistant@2.1.0`

**Comment by jcastro** [comment]
@Bjsulla thanks this worked, however I've partially lost my HomeKit configuration, all my devices are now in "Default Room" while the rest of rooms I've created are empty (but still there). Any idea why this happened? Thanks!

**Comment by Bjsulla** [comment]
@jcastro  #36

**Comment by jcastro** [comment]
@Bjsulla doesn't seem my issue, I have discovery disabled and I don't lose my configuration when restarting... I just lose it now when I changed the version of the plugin :/

**Comment by robbiet480** [comment]
2.2.1 is coming up right now
