### ISSUE TITLE
after update to 2.2.1 homebridge crashes when reloading automations

### ISSUE THREAD

**Issue by rbflurry** [home-assistant/homebridge-homeassistant#192]
I get the following error in the log.

```
Thu, 20 Jul 2017 00:58:33 GMT EventedHTTPServer Server listening on port 51826
/usr/lib/node_modules/homebridge-homeassistant/accessories/switch.js:26
        .setValue(newState.state === 'on', null, 'internal');
                          ^

TypeError: Cannot read property 'state' of null
    at Object.onEvent (/usr/lib/node_modules/homebridge-homeassistant/accessories/switch.js:26:27)
    at EventSource.<anonymous> (/usr/lib/node_modules/homebridge-homeassistant/index.js:58:19)
    at emitOne (events.js:77:13)
    at EventSource.emit (events.js:169:7)
    at _emit (/usr/lib/node_modules/homebridge-homeassistant/node_modules/eventsource/lib/eventsource.js:186:17)
    at parseEventStreamLine (/usr/lib/node_modules/homebridge-homeassistant/node_modules/eventsource/lib/eventsource.js:201:9)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-homeassistant/node_modules/eventsource/lib/eventsource.js:164:11)
    at emitOne (events.js:77:13)
    at IncomingMessage.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)

```

**Comment by robbiet480** [comment]
Are you on 2.2.1? https://github.com/home-assistant/homebridge-homeassistant/releases/tag/2.2.1

**Comment by rbflurry** [comment]
Yes running 2.2.1

**Comment by robbiet480** [comment]
When do you get this error? When the switch turns on or off? Or just when starting up Homebridge?

**Comment by rbflurry** [comment]
Just did some testing an I am able to recreate and crash homebridge by running the automation reload.

![image](https://user-images.githubusercontent.com/22154114/28398702-6d7ce338-6cd6-11e7-9c2c-66c6e1809a0f.png)

**Comment by rbflurry** [comment]
This also seems to happen when groups are reloaded. Anyone else setting this?

**Comment by rbflurry** [comment]
So it looks as though when the groups are reloaded the status is set to null which Homebridge cant handle. See the error log below. I have removed groups from my homebridge config as I do not have a use case right now.

```
[8/2/2017, 10:18:28 AM] [HomeAssistant] Received event: {"data": {"service": "reload", "domain": "group", "service_call_id": "139978910611496-47", "service_data": {}}, "time_fired": "2017-08-02T14:18:28.015118+00:00", "event_type": "call_service", "origin": "LOCAL"}
[8/2/2017, 10:18:28 AM] [HomeAssistant] Received event: {"data": {"new_state": null, "entity_id": "group.outdoor_lights", "old_state": {"last_changed": "2017-08-02T14:15:04.033680+00:00", "entity_id": "group.outdoor_lights", "state": "off", "attributes": {"assumed_state": false, "entity_id": ["light.front_porch", "switch.back_flood", "switch.esp1"], "friendly_name": "Outdoor Lights", "order": 31}, "last_updated": "2017-08-02T14:15:04.033680+00:00"}}, "time_fired": "2017-08-02T14:18:28.497606+00:00", "event_type": "state_changed", "origin": "LOCAL"}
```
