### ISSUE TITLE
Errors on the total connect platform

### ISSUE THREAD

**Issue by RodolfoPortugal** [home-assistant/homebridge-homeassistant#199]
I’m starting at homeassistant and I’m having difficulty setting up

If someone could help me I would be very grateful !!!

I'm sorry if I'm putting my doubt in the wrong place, I tried the request to help in the homeassistant forum, but I did not get a return !!

> NFO:homeassistant.core:Bus:Handling <Event call_service[L]: domain=alarm_control_panel, service=alarm_arm_home, service_data=code=, entity_id=alarm_control_panel.total_connect, service_call_id=4361720496-12>
ERROR:homeassistant.core:Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/homeassistant/core.py", line 1016, in _event_to_service_call
    yield from service_handler.func(service_call)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/homeassistant/components/alarm_control_panel/__init__.py", line 109, in async_alarm_service_handler
    yield from getattr(alarm, method)(code)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/homeassistant/components/alarm_control_panel/totalconnect.py", line 83, in alarm_arm_home
    self._client.arm_stay()
  File "/Users/rodolfoportugal/.homeassistant/deps/total_connect_client/TotalConnectClient.py", line 51, in arm_stay
    self.arm(ARM_TYPE_STAY, location_name)
  File "/Users/rodolfoportugal/.homeassistant/deps/total_connect_client/TotalConnectClient.py", line 62, in arm
    deviceId = self.get_security_panel_device_id(location)
  File "/Users/rodolfoportugal/.homeassistant/deps/total_connect_client/TotalConnectClient.py", line 77, in get_security_panel_device_id
    raise Exception('No security panel found')
Exception: No security panel found

**Comment by schmittx** [comment]
I recommend you post your concern in the Home Assistant [forums](https://community.home-assistant.io) or on the Home Assistant [GitHub](https://github.com/home-assistant/home-assistant), this area is specifically for the Homebridge plugin development which is not related to your concern.

By the way, the error shows that your panel is not being found. Make sure that you have a valid Total Connect subscription and can you confirm that you're able to login to the Total Connect [website](https://rs.alarmnet.com/tc2/) using the same credentials that you're using for Home Assistant. Just some quick advice for you.
