### ISSUE TITLE
Cannot read property 'state' of null

### ISSUE THREAD

**Issue by Merlinuf** [home-assistant/homebridge-homeassistant#217]
This is crashing homebridge all the time.
Please any suggestions?

/usr/local/lib/node_modules/homebridge-homeassistant/accessories/switch.js:35
        .setValue(newState.state === 'on', null, 'internal');
                          ^

TypeError: Cannot read property 'state' of null
    at Object.onEvent (/usr/local/lib/node_modules/homebridge-homeassistant/accessories/switch.js:35:27)
    at EventSource.<anonymous> (/usr/local/lib/node_modules/homebridge-homeassistant/index.js:63:19)
    at emitOne (events.js:77:13)
    at EventSource.emit (events.js:169:7)
    at _emit (/usr/local/lib/node_modules/homebridge-homeassistant/node_modules/eventsource/lib/eventsource.js:186:17)
    at parseEventStreamLine (/usr/local/lib/node_modules/homebridge-homeassistant/node_modules/eventsource/lib/eventsource.js:201:9)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-homeassistant/node_modules/eventsource/lib/eventsource.js:164:11)
    at emitOne (events.js:77:13)
    at IncomingMessage.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)

**Comment by mathewpeterson** [comment]
I am also getting the same error.

**Comment by mgntrn** [comment]
Same error here

**Comment by lajo-osd** [comment]
Me too!

**Comment by christian1986** [comment]
Get the same error! 

/usr/lib/node_modules/homebridge-homeassistant/accessories/switch.js:35
        .setValue(newState.state === 'on', null, 'internal');

**Comment by leapp** [comment]
Me too..... T T

**Comment by dasam** [comment]
#meetoo :-(

**Comment by robbiet480** [comment]
Seems you have a switch that doesn't have a state set... Might want to see if you have any broken entities or something...

**Comment by gretel** [comment]
i feel like this should handled in `homebridge-homeassistant` so it won't crash `homebridge` regardless of it receiving any "broken" data.

```
TypeError: Cannot read property 'state' of null
    at HomeAssistantSwitch.onEvent (/home/tom/homebridge/node_modules/homebridge-homeassistant/accessories/switch.js:35:26)
    at EventSource.HomeAssistantPlatform.es.addEventListener (/home/tom/homebridge/node_modules/homebridge-homeassistant/index.js:63:19)
    at EventSource.emit (events.js:160:13)
    at _emit (/home/tom/homebridge/node_modules/eventsource/lib/eventsource.js:186:17)
    at parseEventStreamLine (/home/tom/homebridge/node_modules/eventsource/lib/eventsource.js:201:9)
    at IncomingMessage.<anonymous> (/home/tom/homebridge/node_modules/eventsource/lib/eventsource.js:164:11)
    at IncomingMessage.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at IncomingMessage.Readable.push (_stream_readable.js:213:10)
```
