### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by michaeldeborst** [home-assistant/homebridge-homeassistant#219]
I've been trying to get this plugin working but my config seems to crash it:
I added it again here: [output](https://pastebin.com/ctTCjY4G)
` 
pi@hassbian:~/.homebridge $ homebridge 
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[9/12/2017, 3:57:31 PM] Loaded plugin: homebridge-homeassistant
[9/12/2017, 3:57:31 PM] Registering platform 'homebridge-homeassistant.HomeAssistant'
[9/12/2017, 3:57:31 PM] ---
[9/12/2017, 3:57:32 PM] Loaded plugin: homebridge-server
[9/12/2017, 3:57:32 PM] Registering platform 'homebridge-server.Server'
[9/12/2017, 3:57:32 PM] ---
[9/12/2017, 3:57:32 PM] Loaded config.json with 0 accessories and 2 platforms.
[9/12/2017, 3:57:32 PM] ---
[9/12/2017, 3:57:32 PM] Loading 2 platforms...
[9/12/2017, 3:57:32 PM] [Homebridge Server] Initializing Server platform...
[9/12/2017, 3:57:32 PM] [HomeAssistant] Initializing HomeAssistant platform...
[9/12/2017, 3:57:32 PM] [HomeAssistant] Fetching HomeAssistant devices.
[9/12/2017, 3:57:32 PM] [Homebridge Server] is listening on: http://192.168.2.30:8765
undefined:1
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request.request [as _callback] (/usr/lib/node_modules/homebridge-homeassistant/index.js:101:38)
    at Request.self.callback (/usr/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:293:19)
`

This is my current config with the personal details blanked out: [Config](https://pastebin.com/UnFjZhAk)

`{
   "bridge":{
      "name":"Homebridge",
      "username":"CC:22:3D:E3:CE:30",
      "port":51826,
      "pin":"031-45-154",
      "manufacturer":"********",
      "model":"Homebridge with Homeassistant",
      "serialNumber":"123.456"
   },
   "platforms":[
      {
         "platform":"Server",
         "port":8765,
         "name":"Homebridge Server",
         "log":"/home/pi/loghome.txt",
         "restart":"sudo reboot now"
      },
      {
         "platform":"HomeAssistant",
         "name":"HomeAssistant",
         "host":"http://********:80",
         "password":"********",
         "supported_types":[
            "input_boolean",
            "switch"
         ],
         "default_visibility":"visible",
         "logging":true,
         "verify_ssl":false
      }
   ]
}`

Can anyone point me in the right direction? I tried deciphering the bottom error message but I ran out of luck.

**Comment by phoenixuprising** [comment]
I'm experiencing the same issue. Did you set it up via the Hassio addon?  Have you been able to make any progress on getting it working?

**Comment by schmittx** [comment]
Are you still experiencing this problem?

**Comment by gerswin** [comment]
same here, any advance?
