### ISSUE TITLE
Error Reading Home Assistant using SSL

### ISSUE THREAD

**Issue by vbtrek** [home-assistant/homebridge-homeassistant#226]
I have homeassistant/home-assistant Docker installed on my Synology NAS with a valid SSL certificate from Namecheap.
I also have marcoraddatz/homebridge Docker installed on my Synology NAS and this plugin.

Install.sh:
```
#!/bin/bash
npm install -g homebridge-homeassistant
```

config.json:
```
{
	"bridge":
	{
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:31",
		"port": 51826,
		"pin": "031-45-154",
		"manufacturer": "@nfarina",
		"model": "Homebridge",
		"serialNumber": "0.4.20"
	},
	"accessories": [ ],
	"platforms": [
	{
	    "platform": "HomeAssistant",
	    "name": "HomeAssistant",
	    "host": "https://mydomain:8123/",
	    "password": "MyPassword",
	    "supported_types": [
		"automation", 
		"binary_sensor", 
		"climate", 
		"cover", 
		"device_tracker", 
		"fan", 
		"group", 
		"input_boolean", 
		"light", 
		"lock", 
		"media_player", 
		"remote", 
		"scene", 
		"sensor", 
		"switch"
	],
	    "default_visibility": "visible",
	    "logging": true,
	    "verify_ssl": true
	}
	]
}
```

I get the following error in the log at startup, then the Docker crashes:
```
at Object.onceWrapper (events.js:314:30)
at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:1091:12)
at Request.emit (events.js:210:7)
at emitOne (events.js:115:13)
at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:1171:10)
at Request.emit (events.js:213:7)
at emitTwo (events.js:125:13)
at Request.self.callback (/usr/local/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:188:22)
at Request.request [as _callback] (/usr/local/lib/node_modules/homebridge-homeassistant/index.js:101:38)
at JSON.parse (<anonymous>)
SyntaxError: Unexpected token : in JSON at position 3

   ^
404: Not Found
undefined:1
e[37m[2017-9-18 19:59:48]e[39m Loading 0 accessories...
e[37m[2017-9-18 19:59:48]e[39m e[36m[HomeAssistant]e[39m Fetching HomeAssistant devices.
e[37m[2017-9-18 19:59:48]e[39m e[36m[HomeAssistant]e[39m Initializing HomeAssistant platform...
e[37m[2017-9-18 19:59:48]e[39m Loading 1 platforms...
e[37m[2017-9-18 19:59:48]e[39m ---
e[37m[2017-9-18 19:59:48]e[39m Loaded config.json with 0 accessories and 1 platforms.
```

Any ideas?

**Comment by vbtrek** [comment]
Solved this, removed the trailing forward slash at the end of the host.
