### ISSUE TITLE
Crash when reading fan speed

### ISSUE THREAD

**Issue by kodek** [home-assistant/homebridge-homeassistant#283]
Not familiar with the API, but should this data.attributes be guarded by a null check? The fields above do it:

https://github.com/home-assistant/homebridge-homeassistant/blob/1a1759b8e47ece5550be627118dd43c3d00a9b7f/accessories/fan.js#L36

From the logs:

[2018-2-10 15:36:59] [HomeAssistant] fetching power state for: Office light
[2018-2-10 15:36:59] [HomeAssistant] fetching brightness for: Office light
[2018-2-10 15:36:59] [HomeAssistant] fetching brightness for: Downstairs hallway light
[2018-2-10 15:36:59] [HomeAssistant] fetching power state for: Downstairs hallway light
[2018-2-10 15:36:59] [HomeAssistant] fetching power state for: Kitchen light
[2018-2-10 15:36:59] [HomeAssistant] fetching brightness for: Kitchen light
[2018-2-10 15:36:59] [HomeAssistant] fetching power state for: Master bedroom fan light
[2018-2-10 15:36:59] [HomeAssistant] fetching brightness for: Master bedroom fan light
/homebridge/node_modules/homebridge-homeassistant/accessories/fan.js:99
          var speedList = data.attributes.speed_list;
                                          ^

TypeError: Cannot read property 'speed_list' of undefined
    at client.fetchState (/homebridge/node_modules/homebridge-homeassistant/accessories/fan.js:99:43)
    at request (/homebridge/node_modules/homebridge-homeassistant/index.js:109:9)
    at Request.request [as _callback] (/homebridge/node_modules/homebridge-homeassistant/index.js:101:7)
    at Request.self.callback (/homebridge/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/homebridge/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/request/request.js:1085:12)

**Comment by kodek** [comment]
I sent out #284 in case the fix is as simple as I hope :)
