### ISSUE TITLE
Home Assistant tries to set temperature to Celsius

### ISSUE THREAD

**Issue by nmajin** [home-assistant/homebridge-homeassistant#306]
I have my Nest thermostat configured with Fahrenheit but it seems like HA is trying to change the temperature in Celsius and is causing issues:

`
2018-02-25 21:51:31 INFO (MainThread) [homeassistant.components.http] Serving /api/services/climate/set_temperature to 10.0.1.1 (auth: True)
2018-02-25 21:51:31 INFO (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=climate, service=set_temperature, service_data=entity_id=climate.home, temperature=15.5, service_call_id=140677742203400-26>
2018-02-25 21:51:31 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall climate.set_temperature: entity_id=['climate.home'], temperature=15.5>
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/core.py", line 1010, in _event_to_service_call
    yield from service_handler.func(service_call)
  File "/usr/src/app/homeassistant/components/climate/__init__.py", line 336, in async_temperature_set_service
    yield from climate.async_set_temperature(**kwargs)
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 327, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 243, in result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/app/homeassistant/components/climate/nest.py", line 173, in set_temperature
    self.device.target = temp
  File "/usr/local/lib/python3.6/site-packages/nest/nest.py", line 510, in target
    self._set('devices/thermostats', data)
  File "/usr/local/lib/python3.6/site-packages/nest/nest.py", line 168, in _set
    response = self._nest_api._put(path=path, data=data)
  File "/usr/local/lib/python3.6/site-packages/nest/nest.py", line 1590, in _put
    return self._request('PUT', path, data=data)
  File "/usr/local/lib/python3.6/site-packages/nest/nest.py", line 1582, in _request
    raise APIError(response)
nest.nest.APIError: Temperature F value is too low: 16.0
2018-02-25 21:51:31 INFO (MainThread) [homeassistant.core] Bus:Handling <Event system_log_event[L]: timestamp=1519613491.485388, level=ERROR, message=Error executing service <ServiceCall climate.set_temperature: entity_id=['climate.home'], temperature=15.5>, exception=Traceback (most recent call last):
  File "/usr/src/app/homeassistant/core.py", line 1010, in _event_to_service_call
    yield from service_handler.func(service_call)
  File "/usr/src/app/homeassistant/components/climate/__init__.py", line 336, in async_temperature_set_service
    yield from climate.async_set_temperature(**kwargs)
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 327, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 243, in result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/app/homeassistant/components/climate/nest.py", line 173, in set_temperature
    self.device.target = temp
  File "/usr/local/lib/python3.6/site-packages/nest/nest.py", line 510, in target
    self._set('devices/thermostats', data)
  File "/usr/local/lib/python3.6/site-packages/nest/nest.py", line 168, in _set
    response = self._nest_api._put(path=path, data=data)
  File "/usr/local/lib/python3.6/site-packages/nest/nest.py", line 1590, in _put
    return self._request('PUT', path, data=data)
  File "/usr/local/lib/python3.6/site-packages/nest/nest.py", line 1582, in _request
    raise APIError(response)
nest.nest.APIError: Temperature F value is too low: 16.0
, source=components/climate/nest.py>
`

**Comment by nmajin** [comment]
Looks like this is similar to: #268. So this is a Home Assistant bug? I am running the latest release and still not seeing a fix. Any input?
