### ISSUE TITLE
Temperature Sensors / Shutters are not included

### ISSUE THREAD

**Issue by fastender** [home-assistant/homebridge-homeassistant#49]
In Home Assistant i can see the Fibaro Shutters on the Dashboard as "Cover" and i can use it in the Browser without problems (arrows open / close).

Homebridge is installed (and well configurated) and things like some Switches (and some Hue Lamps) will be shown in Home App and i can use them with Siri.

My problem is that the Rollershutters (and the temperature sensors) will not be shown in Homebridge, because they are not included.

Is this normal that only Switches will be included into this Homebridge Plugin.

**Comment by maddox** [comment]
It is. Historically, this plugin didn't not bridge Sensors over purposefully. But that's going to change soon. You can [read more here](https://github.com/home-assistant/homebridge-homeassistant/pull/46#issuecomment-251011417).

**Comment by fastender** [comment]
That are wonderful news. This will give more Power and PR for HA.

Rollershutters at the moment then only over "scenes" yes?

**Comment by robbiet480** [comment]
@fastender rollershutter (via the `cover` component) support has been added, as has sensor support, just do `npm install -g home-assistant/homebridge-homeassistant`.

**Comment by fastender** [comment]
Thanks...


but....

**Comment by fastender** [comment]
it doesnt work...

First:

I have first config.json according to the defaults below

https://github.com/home-assistant/homebridge-homeassistant

updated.



Have then with the command

sudo npm install -g homebridge-homeassistant

updated to the latest version.



Property in the config of the HA

   customize:
      cover.rolladen_flur:
        Homebridge_cover_type: rollershutter

      cover.rolladen_links:
        Homebridge_cover_type: rollershutter

      cover.rolladen_rechts:
        Homebridge_cover_type: rollershutter

is added.


HA and Home (IOS) working.


All my Z-Wave devices are running VERA. They all also appear neat in my HA.

PROBLEM: But neither the sensor (bspw Fibaro Smoke Sensor or many other sensors, such as temperature, etc.) or the roller bar (Fibaro Rollershutter) are displayed)

**Comment by robbiet480** [comment]
You need to use `sudo npm install -g home-assistant/homebridge-homeassistant` for now as we have not yet released the updates to npm.

**Comment by fastender** [comment]
yes i made it too following this post:

https://github.com/home-assistant/homebridge-homeassistant/issues/64

**Comment by fastender** [comment]
i make again

**Comment by fastender** [comment]
i enter "homebridge" 

i get this

pi@raspberrypi:~ $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[10/29/2016, 10:19:39 AM] Loaded plugin: homebridge-homeassistant
homebridge API version: 2.1
[10/29/2016, 10:19:39 AM] Registering platform 'homebridge-homeassistant.HomeAssistant'
[10/29/2016, 10:19:39 AM] ---
[10/29/2016, 10:19:39 AM] Loaded config.json with 0 accessories and 1 platforms.
[10/29/2016, 10:19:39 AM] ---
[10/29/2016, 10:19:39 AM] Loading 1 platforms...
[10/29/2016, 10:19:39 AM] [HomeAssistant] Initializing HomeAssistant platform...
Booting Platform
[10/29/2016, 10:19:39 AM] [HomeAssistant] Fetching HomeAssistant devices.
[10/29/2016, 10:19:39 AM] Loading 0 accessories...
Plugin - DidFinishLaunching
[10/29/2016, 10:19:40 AM] [HomeAssistant] Initializing platform accessory 'Notify when someone arrives home'...
[10/29/2016, 10:19:40 AM] [HomeAssistant] Initializing platform accessory '1ddddd'...
[10/29/2016, 10:19:40 AM] [HomeAssistant] Initializing platform accessory 'Rolladen Auf'...
[10/29/2016, 10:19:40 AM] [HomeAssistant] Initializing platform accessory 'Rolladen Runter'...
[10/29/2016, 10:19:40 AM] [HomeAssistant] Initializing platform accessory 'Steckdose 1'...
[10/29/2016, 10:19:40 AM] [HomeAssistant] Initializing platform accessory 'Rauchsensor 1'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 031-45-154 │
    └────────────┘

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at Server._listen2 (net.js:1252:14)
    at listen (net.js:1288:10)
    at Server.listen (net.js:1384:5)
    at EventedHTTPServer.listen (/usr/lib/node_modules/hap-nodejs/lib/util/eventedhttp.js:59:19)
    at HAPServer.listen (/usr/lib/node_modules/hap-nodejs/lib/HAPServer.js:157:20)
    at Bridge.Accessory.publish (/usr/lib/node_modules/hap-nodejs/lib/Accessory.js:496:16)
    at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:111:16)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:369:14)

**Comment by robbiet480** [comment]
1. `EADDRINUSE` means `homebridge` is already running somewhere. Try doing `killall -9 homebridge` to ensure that `homebridge` is not running.
2. You said your config has `Homebridge_cover_type`. It should be `homebridge_cover_type` (lowercase h)

**Comment by fastender** [comment]
ok i make the killall (i had a service for homebridge) -> now killed

yes the config is right (i write here false, but in my raspberry its right):

  customize:
     cover.rolladen_flur:
       homebridge_cover_type: rollershutter
     cover.rolladen_links:
       homebridge_cover_type: rollershutter
     cover.rolladen_rechts:
       homebridge_cover_type: rollershutter



i get


pi@raspberrypi:~ $ killall -9 homebridge
pi@raspberrypi:~ $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[10/29/2016, 10:23:17 AM] Loaded plugin: homebridge-homeassistant
homebridge API version: 2.1
[10/29/2016, 10:23:17 AM] Registering platform 'homebridge-homeassistant.HomeAssistant'
[10/29/2016, 10:23:17 AM] ---
[10/29/2016, 10:23:17 AM] Loaded config.json with 0 accessories and 1 platforms.
[10/29/2016, 10:23:17 AM] ---
[10/29/2016, 10:23:17 AM] Loading 1 platforms...
[10/29/2016, 10:23:17 AM] [HomeAssistant] Initializing HomeAssistant platform...
Booting Platform
[10/29/2016, 10:23:17 AM] [HomeAssistant] Fetching HomeAssistant devices.
[10/29/2016, 10:23:17 AM] Loading 0 accessories...
Plugin - DidFinishLaunching
[10/29/2016, 10:23:17 AM] [HomeAssistant] Initializing platform accessory 'Notify when someone arrives home'...
[10/29/2016, 10:23:17 AM] [HomeAssistant] Initializing platform accessory '1ddddd'...
[10/29/2016, 10:23:17 AM] [HomeAssistant] Initializing platform accessory 'Rolladen Auf'...
[10/29/2016, 10:23:17 AM] [HomeAssistant] Initializing platform accessory 'Rolladen Runter'...
[10/29/2016, 10:23:17 AM] [HomeAssistant] Initializing platform accessory 'Steckdose 1'...
[10/29/2016, 10:23:17 AM] [HomeAssistant] Initializing platform accessory 'Rauchsensor 1'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 031-45-154 │
    └────────────┘

[10/29/2016, 10:23:17 AM] Homebridge is running on port 51826.

**Comment by robbiet480** [comment]
Looks like it's working? "Rolladen auf", "Rolladen Runter"?

**Comment by fastender** [comment]
no, that are scenes that i made in Home Assistant. The scenes are working.

**Comment by robbiet480** [comment]
You added `cover` to `supported_types` in `~/.homebridge/config.json`?

**Comment by fastender** [comment]
the scenes in config are:

scene:
 - name: Rolladen Auf
   entities:
       cover.rolladen_links:
           state: open
       cover.rolladen_rechts:
           state: open
       cover.rolladen_flur:
           state: open

 - name: Rolladen Runter
   entities:
       cover.rolladen_links:
           state: closed
       cover.rolladen_rechts:
           state: closed
       cover.rolladen_flur:
           state: closed




yes config.json is

{
    "bridge": {
        "name": "Homeassistant",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
 
    "platforms": [
        {
            "platform": "HomeAssistant",
            "name": "HomeAssistant",
            "host": "https://XXXX.duckdns.org",
            "password": "XXXX",
		    "supported_types": ["binary_sensor", "cover", "fan", "garage_door", "input_boolean", "light", "lock", "media_player", "rollershutter", "scene", "sensor", "switch"]
        }
     ],
 
    "accessories": []
}

**Comment by fastender** [comment]
I think the reason lies either in the duckdns or vera, that says my feeling..

**Comment by robbiet480** [comment]
That also is my feeling, as long as you are sure that you have the latest version of homebridge-homeassistant.

**Comment by fastender** [comment]
newest yes Home Assistant 0.31.1

I have also noticed that I HA local no longer reach

http://192.168.178.81:8123/

I had set up DuckDNS after this video with this nice guy with the bald head.

**Comment by robbiet480** [comment]
Homebridge should be accessing Home Assistant via the local IP address not DuckDNS. Make sure Home Assistant is on and connectable.

**Comment by fastender** [comment]
that's a problem

About putty or winscp I can achieve

Also via duckdns (with https)

But local, does not go. Irgednwas is wrongly defined there ... I must look ... what went wrong.

**Comment by fastender** [comment]
I will inform you if I have solved this problem again here.

**Comment by fastender** [comment]
Hi back again.

First:


1. I have updated now config.json (host is with https now)

{
    "bridge": {
        "name": "Homeassistant",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
 
    "platforms": [
        {
            "platform": "HomeAssistant",
            "name": "HomeAssistant",
            "host": "https://192.168.178.81:8123/",
            "password": "XXX",
		    "supported_types": ["binary_sensor", "cover", "fan", "garage_door", "input_boolean", "light", "lock", "media_player", "rollershutter", "scene", "sensor", "switch"]
        }
     ],
 
    "accessories": []
}



2. Then in Putty:

pi@raspberrypi:~ $ sudo service homebridge stop
pi@raspberrypi:~ $ sudo service homebridge start
pi@raspberrypi:~ $ killall -9 homebridge
pi@raspberrypi:~ $ sudo npm install -g homebridge-homeassistant
/usr/local/lib
└── homebridge-homeassistant@1.7.0

pi@raspberrypi:~ $ sudo service homebridge start


3. Then:

Before execute homebridge i enter:

export NODE_TLS_REJECT_UNAUTHORIZED=0

(https://github.com/home-assistant/homebridge-homeassistant/issues/10)


pi@raspberrypi:~ $ export NODE_TLS_REJECT_UNAUTHORIZED=0
pi@raspberrypi:~ $ sudo service homebridge start
pi@raspberrypi:~ $ sudo reboot


4. Then I deleted with WinSCP

in /home/pi/.homebridge/accessories
in /home/pi/.homebridge/persist

the included files


5. Homebridge was not started

I had manually start

pi@raspberrypi:~ $ homebridge


*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of                                         Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libd                                        ns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not su                                        pported (or only supported partially) in the Apple Bonjour compatibility layer o                                        f Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libd                                        ns_sd&e=node&f=DNSServiceRegister>
[10/29/2016, 5:09:47 PM] Loaded plugin: homebridge-homeassistant
homebridge API version: 2.1
[10/29/2016, 5:09:47 PM] Registering platform 'homebridge-homeassistant.HomeAssi                                        stant'
[10/29/2016, 5:09:47 PM] ---
[10/29/2016, 5:09:47 PM] Loaded config.json with 0 accessories and 1 platforms.
[10/29/2016, 5:09:47 PM] ---
[10/29/2016, 5:09:48 PM] Loading 1 platforms...
[10/29/2016, 5:09:48 PM] [HomeAssistant] Initializing HomeAssistant platform...
Booting Platform
[10/29/2016, 5:09:48 PM] [HomeAssistant] Fetching HomeAssistant devices.
[10/29/2016, 5:09:48 PM] Loading 0 accessories...
Plugin - DidFinishLaunching
[10/29/2016, 5:09:48 PM] [HomeAssistant] Failed getting devices: Error: Hostname                                        /IP doesn't match certificate's altnames: "IP: 192.168.178.81 is not in the cert                                        's list: ". Retrying...
[10/29/2016, 5:09:53 PM] [HomeAssistant] Fetching HomeAssistant devices.
[10/29/2016, 5:09:53 PM] [HomeAssistant] Failed getting devices: Error: Hostname/IP doesn't match certificate's altnames: "IP: 192.168.178.81 is not in the cert's list: ". Retrying...
[10/29/2016, 5:09:58 PM] [HomeAssistant] Fetching HomeAssistant devices.
[10/29/2016, 5:09:58 PM] [HomeAssistant] Failed getting devices: Error: Hostname/IP doesn't match certificate's altnames: "IP: 192.168.178.81 is not in the cert's list: ". Retrying...


6. I stop homebridge and enter

Before execute homebridge i enter:

pi@raspberrypi:~ $ export NODE_TLS_REJECT_UNAUTHORIZED=0

(https://github.com/home-assistant/homebridge-homeassistant/issues/10)



7. 

pi@raspberrypi:~ $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[10/29/2016, 5:11:55 PM] Loaded plugin: homebridge-homeassistant
homebridge API version: 2.1
[10/29/2016, 5:11:55 PM] Registering platform 'homebridge-homeassistant.HomeAssistant'
[10/29/2016, 5:11:55 PM] ---
[10/29/2016, 5:11:55 PM] Loaded config.json with 0 accessories and 1 platforms.
[10/29/2016, 5:11:55 PM] ---
[10/29/2016, 5:11:55 PM] Loading 1 platforms...
[10/29/2016, 5:11:55 PM] [HomeAssistant] Initializing HomeAssistant platform...
Booting Platform
[10/29/2016, 5:11:56 PM] [HomeAssistant] Fetching HomeAssistant devices.
[10/29/2016, 5:11:56 PM] Loading 0 accessories...
Plugin - DidFinishLaunching
[10/29/2016, 5:11:56 PM] [HomeAssistant] Initializing platform accessory 'Rolladen Runter'...
[10/29/2016, 5:11:56 PM] [HomeAssistant] Initializing platform accessory 'Steckdose 1'...
[10/29/2016, 5:11:56 PM] [HomeAssistant] Initializing platform accessory 'Notify when someone arrives home'...
[10/29/2016, 5:11:56 PM] [HomeAssistant] Initializing platform accessory 'Rolladen Auf'...
[10/29/2016, 5:11:56 PM] [HomeAssistant] Initializing platform accessory '1ddddd'...
[10/29/2016, 5:11:56 PM] [HomeAssistant] Initializing platform accessory 'Rauchsensor 1'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 031-45-154 │
    └────────────┘

[10/29/2016, 5:11:56 PM] Homebridge is running on port 51826.


FINALLY: But no sensors or rollershutter... i dont know...

**Comment by fastender** [comment]
i add

 "ssl": true,

into the config

{
    "bridge": {
        "name": "Homeassistant",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
		"ssl": true,
        "pin": "031-45-154"
    },
 
    "platforms": [
        {
            "platform": "HomeAssistant",
            "name": "HomeAssistant",
            "host": "https://192.168.178.81:8123/",
            "password": "mypassword",
		    "supported_types": ["binary_sensor", "cover", "fan", "garage_door", "input_boolean", "light", "lock", "media_player", "rollershutter", "scene", "sensor", "switch"]
        }
     ],
 
    "accessories": []
}


but no changes :(

**Comment by fastender** [comment]
Ok i now make fresh install using 

HASSbian (Link: https://github.com/home-assistant/pi-gen)

Then: Homebridge (Link: https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi)

Then: Home Assistant for Homebridge (Link: https://github.com/home-assistant/homebridge-homeassistant)

Config for Homebridge using:

{
    "bridge": {
        "name": "Homeassistant",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
 
    "platforms": [
        {
            "platform": "HomeAssistant",
            "name": "HomeAssistant",
            "host": "http://192.168.178.81:8123/",
            "password": "raspberry",
		    "supported_types": ["binary_sensor", "cover", "fan", "garage_door", "input_boolean", "light", "lock", "media_player", "rollershutter", "scene", "sensor", "switch"]
        }	
		

     ],
 
    "accessories": []
}

**Comment by fastender** [comment]
no SSL, no DuckDNS installed...

and again:

no sensors, no temperature, no rollershutters

**Comment by fastender** [comment]
i check now my config again

only this errors come:

16-10-29 20:27:11 homeassistant.components.light.hue: Connected to Hue at 192.168.178.88 but not registered.
16-10-29 20:27:38 plexapi: https://192-168-178-76.70be15f8bf8d4938949e422a5a573595.plex.direct:32400: HTTPSConnectionPool(host='192-168-178-76.70be15f8bf8d4938949e422a5a573595.plex.direct', port=32400): Max retries exceeded with url: /?X-Plex-Token=tgrAb6vpcfz68QdnLSVy (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x6cc8e210>: Failed to establish a new connection: [Errno -2] Name or service not known',))
16-10-29 20:28:11 netdisco.ssdp: Error fetching description at http://192.168.178.105:8200/rootDesc.xml

I think this errors are not important.


I think the problem come from the vera component. It is very probably caused by Vera.

Here I read the following:

https://home-assistant.io/components/vera/

(...)
By default your switches will be added to Home Assistant as switches, however if some of them are light switches, you can tell Home Assistant this using the optional lights parameter as shown below.
(...)

Can it be that I have the sensors or roller shutters here specifically expressly?

**Comment by fastender** [comment]
i give now:

vera:
  vera_controller_url: http://192.168.178.109:3480/
  sensors: [28, 35, 39]

but i think that only lights can be written. i think vera component must be updated.

**Comment by fastender** [comment]
i have invalid error message invalid config:

The following platforms contain invalid configuration: vera (please check your configuration)

**Comment by fastender** [comment]
error comes from vera component.

**Comment by fastender** [comment]
Today is a new day.

And its wonderful.

:)

Instead of doing npm install -g homebridge-homeassistant i make sudo npm install -g home-assistant/homebridge-homeassistant to install it from Github directly.

And i see now a lot of new sensors, rollershutters and temperatures... :)

WONDERFUL.

MANY THANKS!
