### ISSUE TITLE
TypeError: Cannot read property 'username' of undefined

### ISSUE THREAD

**Issue by oguinjr** [home-assistant/homebridge-homeassistant#58]
I have a RBP3 and get this message when starting homebridge.

TypeError: Cannot read property 'username' of undefined
at Server.loadConfig (/usr/local/lib/nodemodules/homebridge/lib/server.js:199:31)
at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:49:23)
at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
at Object. (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Function.Module.runMain (module.js:441:10)
at startup (node.js:134:18)

This is what my config.json looks like.

{
"Bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:30",
"port": 51826,
"pin": "031-45-154"
},
"platforms": [
{
"platform": "HomeAssistant",
"name": "HomeAssistant",
"host": "http://***.***.*.**:8123",
"password": "***",
"supported_types": ["light"]
}]
}

**Comment by robbiet480** [comment]
This appears to be a problem with homebridge not homebridge-homeassistant. Please take the issue to their repository instead. Thanks!
