### ISSUE TITLE
Cannot add a bridged Accessory with the same UUID as another bridged Accessory

### ISSUE THREAD

**Issue by snizzleorg** [home-assistant/homebridge-homeassistant#7]
Apparently some of my devices have the same name. 

```
[4/29/2016, 7:59:59 PM] [HomeAssistant] Initializing platform accessory 'television'...
[4/29/2016, 7:59:59 PM] [HomeAssistant] Initializing platform accessory 'FIBARO System FGS222 Double Relay Switch 2x1.5kW Switch'...
[4/29/2016, 7:59:59 PM] [HomeAssistant] Initializing platform accessory 'Wenzhou TKB Control System TZ66D Dual Wall Switch Switch'...
[4/29/2016, 7:59:59 PM] [HomeAssistant] Initializing platform accessory 'FIBARO System FGS222 Double Relay Switch 2x1.5kW Switch'...
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:219
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
      ^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 819122ee-5ae0-4ddd-80ee-e6531dcee5c1
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:219:13)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:346:24)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at /usr/local/lib/node_modules/homebridge-homeassistant/index.js:146:7
    at Request.onResponse [as _callback] (/usr/local/lib/node_modules/homebridge-homeassistant/index.js:79:7)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:200:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:1067:10)
    at emitOne (events.js:95:20)
```

I can't really change this since those are z-wave devices which are named automatically - they actually don't really have the same name but maybe the name is too long? and therefore gets truncated?

```
switch.wenzhou_tkb_control_system_tz66d_dual_wall_switch_switch_66
switch.wenzhou_tkb_control_system_tz66d_dual_wall_switch_switch_71
```
and maybe 

```
switch.fibaro_system_fgs221_double_relay_switch_2x15kw_switch_25
switch.fibaro_system_fgs221_double_relay_switch_2x15kw_switch_25_2
switch.fibaro_system_fgs221_double_relay_switch_2x15kw_switch_26
switch.fibaro_system_fgs221_double_relay_switch_2x15kw_switch_26_2
switch.fibaro_system_fgs221_double_relay_switch_2x15kw_switch_3
switch.fibaro_system_fgs221_double_relay_switch_2x15kw_switch_4
switch.fibaro_system_fgs221_double_relay_switch_2x15kw_switch_4_2
switch.fibaro_system_fgs222_double_relay_switch_2x15kw_switch_68
switch.fibaro_system_fgs222_double_relay_switch_2x15kw_switch_68_2
```
are somehow causing the problems?

I actually don't really need all of those in homekit but it seems there is no way to omit some. Can't homebridge-homeassistant just ignore the devices with same name or iterate them?

**Comment by snizzleorg** [comment]
Nobody has an idea about this?

**Comment by jbardi** [comment]
Apparently the dev doesn't have more than 1 z-wave device of any particular type, so maybe he isn't able to test and realize the problem. I have 23 window/door sensors, all by the same company, all with the exact same name other than the z-wave node id, so I assume they have the same UUID, much like iBeacons from the same company all have the same UUID. This plug is definitely broken if you have more than 1 of the same device on a z-wave network, so back to the drawing board.

I've had to setup an HA Bridge (virtual hue bridge) and use that with the hue bridge plugin of Home Bridge as the only way to be able to control my Home Assistant devices as this plugin is not ready for prime time.

**Comment by robbiet480** [comment]
I don't have this issue. I have 4 of the exact same model Linear switches on my Z-Wave network. @maddox can you weigh in?

**Comment by snizzleorg** [comment]
To me it seemed as the device names get truncated maybe?

**Comment by maddox** [comment]
I don't have multiple z-wave devices of the same type, and I'd have to look up how the UUIDs are being generated 😝

**Comment by javefang** [comment]
looking at your logs it seems that all your z-wave switches have the same friendly name (display name). home assistant might given them a different id by appending numbers but friendly name is the one used by siri to recognise your switch and have to be unique.

you could try to assign friendly_name / homebridge_name in the home assistant's customisation config.


e.g.

```
homeassistant:
   customize:
    switch.living_room:
      homebridge_name: 'Living Room Floor Light'
    switch.living_room_2:
      homebridge_name: 'Living Room Downlight'
```

Restart homebridge and it should pick it up.

**Comment by rogersmj** [comment]
I was having this same problem because I had several friendly names that were the same (didn't matter in Home Assistant UI). Setting unique homebridge_name params for them worked.

**Comment by robbiet480** [comment]
Closed via #54

**Comment by sb13054** [comment]
I'm having an issue with wink2 plugin with invalid UUID.  I'm running this on raspberry Pi3.
 Below is my config file and log

{
    "bridge": {
            "name": "Homebridge",
            "username": “ab:22:3D:E3:CE:30",
            "port": 51826,
            "pin": "031-45-154"
    },
"platforms": [
   	{
   		"platform": "Wink2",
   		"name": "Wink2",
   		"username": “xyz@gmail.com",
   		"password": “xyzzy”,
   		"client_id": “xxxxxxx”,
   		"client_secret": “xxxxxxx”,
   		"hide_groups": ["garage_door", "thermostat"],
   		"hide_ids": [],
   		"fan_ids": []
   	}
   ]
}

LOG

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[6/11/2017, 12:59:57 PM] Loaded plugin: homebridge-liftmaster2
[6/11/2017, 12:59:57 PM] Registering platform 'homebridge-liftmaster2.LiftMaster2'
[6/11/2017, 12:59:57 PM] ---
[6/11/2017, 12:59:58 PM] Loaded plugin: homebridge-nest
[6/11/2017, 12:59:58 PM] Registering platform 'homebridge-nest.Nest'
[6/11/2017, 12:59:58 PM] ---
[6/11/2017, 1:00:00 PM] Loaded plugin: homebridge-wink2
[6/11/2017, 1:00:00 PM] Registering platform 'homebridge-wink2.Wink2'
[6/11/2017, 1:00:00 PM] ---
[6/11/2017, 1:00:00 PM] Loaded config.json with 0 accessories and 1 platforms.
[6/11/2017, 1:00:00 PM] ---
[6/11/2017, 1:00:00 PM] Loading 1 platforms...
[6/11/2017, 1:00:00 PM] [Wink2] Initializing Wink2 platform...
[6/11/2017, 1:00:00 PM] [Wink2] Wink2 Init - Version 2.0.8
Load homebridge-liftmaster2.LiftMaster2
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[6/11/2017, 1:00:00 PM] [Wink2] Reclaiming: Akshar's Light - ID 297278 - TYPE binary_switch
[6/11/2017, 1:00:00 PM] [Wink2] Reclaiming: Akshar's Fan - ID 297279 - TYPE binary_switch
[6/11/2017, 1:00:00 PM] [Wink2] Reclaiming: Media Room - ID 299589 - TYPE binary_switch
[6/11/2017, 1:00:00 PM] [Wink2] Reclaiming: Media Room - ID 299590 - TYPE binary_switch
[6/11/2017, 1:00:00 PM] [Wink2] Reclaiming: Bottom Light Load - ID 470043 - TYPE binary_switch
[6/11/2017, 1:00:00 PM] [Wink2] Reclaiming: Top Light Load - ID 470044 - TYPE binary_switch
[6/11/2017, 1:00:00 PM] [Wink2] Direct Access NOT Enabled. Add direct_access:true to your config if you which to use direct access on Wink.
[6/11/2017, 1:00:00 PM] [homebridge-liftmaster2.LiftMaster2] Please setup MyQ login information!
[6/11/2017, 1:00:00 PM] Homebridge is running on port 51826.
[6/11/2017, 1:00:01 PM] [Wink2] Wink Authentication Successful.
/usr/local/lib/node_modules/homebridge/lib/platformAccessory.js:17
  if (!uuid.isValid(UUID)) throw new Error("UUID '" + UUID + "' is not a valid UUID. Try using the provided 'generateUUID' function to create a valid UUID from any arbitrary string, like a serial number.");
                           ^

Error: UUID '924f20c0-eb15-0131-e510-1e5449afed4e' is not a valid UUID. Try using the provided 'generateUUID' function to create a valid UUID from any arbitrary string, like a serial number.
    at new PlatformAccessory (/usr/local/lib/node_modules/homebridge/lib/platformAccessory.js:17:34)
    at Wink2.addAccessoryCharacteristics (/usr/local/lib/node_modules/homebridge-wink2/index.js:133:24)
    at Wink2.addAccessory (/usr/local/lib/node_modules/homebridge-wink2/index.js:123:10)
    at winkapiv2._deviceReceiptProcessor (/usr/local/lib/node_modules/homebridge-wink2/lib/winkapi.js:222:22)
    at winkapiv2.<anonymous> (/usr/local/lib/node_modules/homebridge-wink2/lib/winkapi.js:119:28)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-wink2/lib/winkapi.js:361:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by skalavala** [comment]
I ran into this problem after adding a bunch of zwave devices to my collection at home. Adding `homebridge_name:` attribute to each exposed entity in Home Assistant fixed it. Thanks @javefang!

Here is what I have for each of the entity/item that I expose to both alexa using `emulated_hue` and Apple Home using `homebridge` in the customize section.

```
light.family_room:
  friendly_name: Family Room Lights
  emulated_hue: true
  emulated_hue_name: Family Room Lights
  homebridge_hidden: false
  homebridge_name: Family Room Lights
```
I wish the error messages are a bit more friendly. Hopefully this will help someone!
