### ISSUE TITLE
crashes upon adding to config.json

### ISSUE THREAD

**Issue by lagunacomputer** [home-assistant/homebridge-homeassistant#78]
Homebridge crashes on load everytime I add/replace the platforms statement in config.json, any ideas?

```json
{"platforms": [
  {
    "platform": "HomeAssistant",
    "name": "HomeAssistant",
    "host": "http://192.168.1.109:8123",
    "password": "pi",
    "supported_types": ["binary_sensor", "cover", "fan", "input_boolean", "light", "lock", "media_player", "scene", "sensor", "switch"]
  }
]}
```

I have spent hours and tried everything, thanks (commas, adding to the EOF, replacing existing0

**Comment by kolossboss** [comment]
Looks ok.
How did you start homebridge? 
Nothing in the log?

**Comment by saisupriyacv** [comment]
Homebridge fails to load home assistant every time It says 

/usr/local/lib/node_modules/homebridge-homeassistant/accessories/sensor.js:44
class HomeAssistantSensor {
^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Plugin.module.exports [as initializer] (/usr/local/lib/node_modules/homebridge-homeassistant/index.js:27:32)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:130:14)
    at Array.forEach (native)
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:108:22)

**Comment by robbiet480** [comment]
@lagunacomputer I need more information. What's the error say?

@saisupriyacv You need to upgrade to a newer version of Node.js.

**Comment by bachoo786** [comment]
I get the following errors:

 Loaded plugin: homebridge-homeassistant
[2/9/2017, 6:43:54 PM] Registering platform 'homebridge-homeassistant.HomeAssistant'
[2/9/2017, 6:43:54 PM] ---
/usr/lib/node_modules/homebridge/lib/server.js:202
  var username = config.bridge.username;
                              ^

TypeError: Cannot read property 'username' of undefined
    at Server._loadConfig (/usr/lib/node_modules/homebridge/lib/server.js:202:31)
    at new Server (/usr/lib/node_modules/homebridge/lib/server.js:52:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

**Comment by robbiet480** [comment]
@bachoo786 This is a problem with Homebridge, not homebridge-homeassistant. I assume your configuration is invalid.

**Comment by bachoo786** [comment]
Here is my config:

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": "45201",
		"pin": "raspberry"
	},

	{
		"platforms": [{
			"platform": "HomeAssistant",
			"name": "HomeAssistant",
			"host": "http://XXXXX",
			"password": “XXXXX",
			"supported_types": ["binary_sensor", "cover", "fan", "input_boolean", "light", "lock", "media_player", "scene", "sensor", "switch"]
		}]
	}

**Comment by lagunacomputer** [comment]
I noticed you have a different homebridge config.json format than I do, PIN and PORT but no Password

**Comment by bachoo786** [comment]
I resolved somehow but mqtt is giving me problems my config now is:

{
	"bridge": {
		"name": "Homebridge",
		"username": “XX:XX:XX:XX:XX:XX",
		"port": XXXXX,
		"pin": “XXX-XX-XXX"
	},

	"platforms": [{
			"platform": "HomeAssistant",
			"name": "HomeAssistant",
			"host": “XXX",
			"password": “XXX",
			"supported_types": ["light", "switch", "media_player"]
		},

		"platforms": [{
			"platforms": "mqtt",
			"name": "mqtt",
			"url": "http://XXX",
			"topic_prefix": “XXX",
			"username": “XXX",
			"password": “XXX"
		}]
	}

**Comment by bachoo786** [comment]
all sorted thanks
