### ISSUE TITLE
Homebridge crashes on load

### ISSUE THREAD

**Issue by itsfrosty** [home-assistant/homebridge-homeassistant#83]
I have my home assistant running using duckdns and letsencrypt certificate. Homebridge home-assistant plugin crashes on starting homebridge. 

Home Assistant version: 0.35.3
Homebridge version: 0.4.16

```
undefined:1
<!doctype html>
^

SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request.onResponse [as _callback] (/usr/local/lib/node_modules/homebridge-homeassistant/index.js:97:19)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:186:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:1081:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-homeassistant/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:260:16)
```

Let me know if I can provide any more details to help debug this. Thanks!

**Comment by olines** [comment]
I am getting the same (not using letsencrypt though).

`undefined:1 
<!doctype html> 
^`

**Comment by robbiet480** [comment]
There's something wrong with how you are connecting to Home Assistant. Perhaps you are connecting through a gateway or using the wrong URL. Not much we can do to help without knowing your exact setup. Make sure you are providing the correct address for the `host` parameter in your Homebridge config.
